#!/bin/bash

cd /home/user/Receitas/
echo "Fazendo backup dos arquivos do diretório Receitas para gerar chave:"
tar -czf backup.tar.gz ./*
echo "Backup concluído com sucesso!"
chaveReceitas=$(sha256sum backup.tar.gz | awk '{print $1}')
sha256sum backup.tar.gz | awk '{print $1}' > chave.txt
rm -rf backup.tar.gz
rm chave.txt
cd /home/user/Modelo/
chaveModelo=$(cat chave.txt)
echo ""
echo "Comparando diretórios de acordo com as suas respectivas chaves..."

if [ $chaveReceitas = $chaveModelo ];
then
    echo "Chave de Receitas:" $chaveReceitas
    echo "Chave de Modelo:" $chaveModelo
    echo "Diretórios iguais, não há necessidade de reparos!"
else
    echo "Chave de Receitas:" $chaveReceitas
    echo "Chave de Modelo:" $chaveModelo
    echo "Diretórios diferentes, há necessidade de reparos!"
    echo ""
    echo "Iniciando sessão de reparos:"
    echo "Removendo arquivos do diretório Receitas..."
    cd /home/user/Receitas/
    rm ./*
    echo "Arquivos removidos"
    echo ""
    echo "Extraindo arquivos de Modelo e enviando para Receitas..."
    cd /home/user/Modelo/
    unzip backup.zip -d /home/user/Receitas/
    echo "Extração finalizada!"
    echo ""
    echo "Fazendo novo backup dos arquivos de Receitas para gerar chave"
    cd /home/user/Receitas/
    tar -czf backup.tar.gz ./*
    sha256sum backup.tar.gz | awk '{print $1}' > /home/user/Modelo/chave.txt
    rm -rf backup.tar.gz
    echo "Sessão de reparos finalizada!"

    sendemail -f "emailInstitucional" \
            -t "emailDestinatario" \
            -u "Modificações nos Arquivos" \
            -m "Foram detectadas modificações em arquivos de seu diretório. A restauração dos arquivos modificados foi realizada com êxito." \
            -s cupijo.ufpa.br:587 \
            -xu "emailInstitucional" \
            -xp "senhaInstitucional"
fi